// students.js
import inosuke from "./assets/inosuke.jpg"
import tangiro from "./assets/tangiro.jpg"
import profile from "./assets/profile.jpg"
const students = [
  {
    name: "Venkatesh",
    age: 22,
    branch: "ECE",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "B-ve",
    image:tangiro,
    address: {
      village: "Chakipalli",
      pin: 532201,
      mandal: "Tekkali",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Ramesh",
    age: 21,
    branch: "CSE",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "O+ve",
    image:inosuke,
    address: {
      village: "Narasannapeta",
      pin: 532421,
      mandal: "Narasannapeta",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Suresh",
    age: 23,
    branch: "EEE",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "A+ve",
    image:profile,
    address: {
      village: "Tekkali",
      pin: 532202,
      mandal: "Tekkali",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Mahesh",
    age: 22,
    branch: "MECH",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "AB+ve",
    image:profile,
    address: {
      village: "Palasa",
      pin: 532221,
      mandal: "Palasa",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Kiran",
    age: 21,
    branch: "IT",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "O-ve",
    image:profile,
    address: {
      village: "Ichapuram",
      pin: 532312,
      mandal: "Ichapuram",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Anil",
    age: 22,
    branch: "CSE",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "B+ve",
    image:profile,
    address: {
      village: "Sompeta",
      pin: 532284,
      mandal: "Sompeta",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Praveen",
    age: 23,
    branch: "ECE",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "A-ve",
    image:profile,
    address: {
      village: "Amadalavalasa",
      pin: 532185,
      mandal: "Amadalavalasa",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Lokesh",
    age: 22,
    branch: "Civil",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "O+ve",
    image:profile,
    address: {
      village: "Rajam",
      pin: 532127,
      mandal: "Rajam",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Sai Kumar",
    age: 21,
    branch: "IT",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "AB-ve",
    image:profile,
    address: {
      village: "Pathapatnam",
      pin: 532213,
      mandal: "Pathapatnam",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    },
  },
  {
    name: "Harish",
    age: 22,
    branch: "EEE",
    college: "Vignan Institute of Information Technology",
    bloodGroup: "B+ve",
    image:profile,
    address: {
      village: "Kaviti",
      pin: 532322,
      mandal: "Kaviti",
      dist: "Srikakulam",
      state: "Andhra Pradesh",
    }},
];

export default students;